---
# tasks file for ansible-role-nsd
- name: Install NSD name server with apt
  apt: name=nsd update_cache=yes cache_valid_time=3600 state=latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install NSD name server with yum
  yum: name=nsd state=installed
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Oracle Linux'

#- name: Create chroot dir
#  file:
#  - path: "{{ nsd_chroot_dir }}"
#  - state: directory
#  - mode: 0755
#  - owner: "{{ nsd_username }}"
#  - group: "{{ nsd_username }}"
#  when: nsd_chroot_dir is defined

- name: Create SSL keys and certificates
  command: nsd-control-setup creates=/etc/nsd/nsd_control.pem
  when: nsd_remote_control_enable == "yes"
  notify:
    - restart nsd

- name: Create config file
  template:
    src: nsd.conf.j2
    dest: /etc/nsd/nsd.conf
    owner: root
    group: root
    mode: 0644
    validate: 'nsd-checkconf %s'
  notify:
    - restart nsd

- name: Enable NSD on boot and start it
  service:
    name: nsd
    state: started
    enabled: true

- name: Setup ufw firewall rule
  ufw:
    rule: allow
    port: "{{ nsd_port }}"
  when: nsd_setup_ufw
